# Some nGram Analysis of the FAIR-CARE Survey Text Responses

In [1]:

import pandas as pd

processed_survey_path = '/home/ekansa/oc-data/fair-care-survey-processed.csv' # Keep this OUT of version control, has sensitive info
ngram_freq_path = '/home/ekansa/oc-data/fair-care-ngram-freq.csv'

df = pd.read_csv(processed_survey_path, low_memory=False)
df_ngram = pd.read_csv(ngram_freq_path, low_memory=False)

print(f'FAIR+CARE survey has {len(df.index)} rows')
print(f'FAIR+CARE survey ngram extract has {len(df_ngram.index)} rows')

FAIR+CARE survey has 787 rows
FAIR+CARE survey ngram extract has 396811 rows

In [2]:
gen_group_cols = ['column', 'ngram_len', 'ngram',]
df_ngram_gp1 = df_ngram[(gen_group_cols + ['ngram_count',])].groupby(gen_group_cols, as_index=False).sum()
df_ngram_gp1.sort_values(by=['column', 'ngram_count',], ascending=[True, False], inplace=True)
print(f'There are {len(df_ngram_gp1.index)} unique ngrams')

# Repeatly used ngrams
rep_ngram_index = df_ngram_gp1['ngram_count'] >= 10
print(f'There are {len(df_ngram_gp1[rep_ngram_index].index)} unique ngrams used 10 or more times')

df_ngram_gp1[rep_ngram_index].head(100)

There are 216120 unique ngrams
There are 1691 unique ngrams used 10 or more times

,column,ngram_len,ngram,ngram_count
248,"Accessible: Additional info, Text",2,data is,13
7531,Application of Ethical Frameworks: Text,2,not sure,20
8073,Application of Ethical Frameworks: Text,2,t know,17
9282,Application of Ethical Frameworks: Text,3,don t know,17
8370,Application of Ethical Frameworks: Text,2,try to,14
...,...,...,...,...
193834,Security: Data Security Measures,4,on devices and files,267
193841,Security: Data Security Measures,4,password protection on devices,267
193854,Security: Data Security Measures,4,protection on devices and,267
194190,Security: Data Security Measures,5,password protection on devices and,267
194200,Security: Data Security Measures,5,protection on devices and files,267

In [3]:
gen_group_cols = ['Section', 'ngram_len', 'ngram',]
df_ngram_gp2 = df_ngram[(gen_group_cols + ['ngram_count',])].groupby(gen_group_cols, as_index=False).sum()
df_ngram_gp2.sort_values(by=['Section', 'ngram_count',], ascending=[True, False], inplace=True)
print(f'There are {len(df_ngram_gp1.index)} unique ngrams')

There are 216120 unique ngrams

In [4]:
# Repeatly used ngrams
# First Show results for the CARE
ngram_count_threshold = 10
section = 'CARE'
rep_ngram_index = ((df_ngram_gp2['ngram_count'] >= ngram_count_threshold) & (df_ngram_gp2['ngram_len'] >= 3) & df_ngram_gp2['Section'].isin([section]))
print(f'There are {len(df_ngram_gp2[rep_ngram_index].index)} unique ngrams used {ngram_count_threshold} or more times with {section} responses')

df_ngram_gp2[rep_ngram_index].head(50)

There are 104 unique ngrams used 10 or more times with CARE responses

       Section  ngram_len                                  ngram  ngram_count
29885     CARE          3                             don t know          105
65975     CARE          4                           i don t know           87
26544     CARE          3                           case by case           39
40407     CARE          3              or descendant communities           39
34786     CARE          3                 indigenous peoples and           34
26190     CARE          3                          by case basis           30
58806     CARE          4                     case by case basis           30
49024     CARE          3                  to indigenous peoples           29
21132     CARE          3                              a case by           27
53123     CARE          4                         a case by case           27
39929     CARE          3                              on a case           24
73052     CARE          4                           on a case by           24
87161     CARE          5                   a case by case basis           24
106567    CARE          5                      on a case by case           24
23361     CARE          3                      and or descendant           23
50905     CARE          3                         we are working           22
23006     CARE          3             and descendant communities           21
29134     CARE          3                         depends on the           21
41470     CARE          3                         peoples and or           20
67627     CARE          4              indigenous peoples and or           20
43475     CARE          3                  related to indigenous           19
52336     CARE          3                   work with indigenous           19
55429     CARE          4          and or descendant communities           19
74663     CARE          4              peoples and or descendant           19
101321    CARE          5   indigenous peoples and or descendant           19
108125    CARE          5  peoples and or descendant communities           19
24875     CARE          3                             as well as           18
28789     CARE          3                        data related to           18
33603     CARE          3                               i try to           16
34805     CARE          3                  indigenous peoples or           16
29896     CARE          3                            don t think           15
51870     CARE          3                with indigenous peoples           15
65980     CARE          4                          i don t think           15
24811     CARE          3                             as part of           14
33243     CARE          3                      human remains and           14
33428     CARE          3                           i googled it           14
33638     CARE          3                              i work in           14
33644     CARE          3                            i work with           14
39669     CARE          3                            of the data           14
34352     CARE          3                           in the field           13
34610     CARE          3              indigenous and descendant           13
37078     CARE          3                             m not sure           13
38590     CARE          3                             none of my           13
39393     CARE          3                  of indigenous peoples           13
41508     CARE          3                  peoples or descendant           13
50355     CARE          3                    use indigenous data           13
52517     CARE          3                          would like to           13
66125     CARE          4                           i m not sure           13
67660     CARE          4       indigenous peoples or descendant           13
68939     CARE          4                      it depends on the           13

In [5]:
# Repeatly used ngrams
# First Show results for the CARE
ngram_count_threshold = 10
section = 'FAIR'
rep_ngram_index = ((df_ngram_gp2['ngram_count'] >= ngram_count_threshold) & (df_ngram_gp2['ngram_len'] >= 3) & df_ngram_gp2['Section'].isin([section]))
print(f'There are {len(df_ngram_gp2[rep_ngram_index].index)} unique ngrams used {ngram_count_threshold} or more times with {section} responses')

df_ngram_gp2[rep_ngram_index].head(50)

There are 1289 unique ngrams used 10 or more times with FAIR responses

       Section  ngram_len                                  ngram  ngram_count
136303    FAIR          3                      devices and files          267
140451    FAIR          3                         on devices and          267
141161    FAIR          3                 password protection on          267
141719    FAIR          3                  protection on devices          267
154004    FAIR          4                   on devices and files          267
154731    FAIR          4         password protection on devices          267
155269    FAIR          4              protection on devices and          267
168053    FAIR          5     password protection on devices and          267
168545    FAIR          5        protection on devices and files          267
133790    FAIR          3                     and system updates          257
142100    FAIR          3                   regular software and          257
143080    FAIR          3                    software and system          257
155624    FAIR          4            regular software and system          257
156598    FAIR          4            software and system updates          257
168878    FAIR          5    regular software and system updates          257
136747    FAIR          3                    explanation of what          244
137555    FAIR          3                      handled data that          244
138392    FAIR          3               information handled data          244
139603    FAIR          3            missing information handled          244
139604    FAIR          3                         missing or why          244
139605    FAIR          3                     missing parts with          244
139921    FAIR          3                      no explanation of          244
141150    FAIR          3                          parts with no          244
143845    FAIR          3                       that was missing          244
145412    FAIR          3                         was missing or          244
145413    FAIR          3                      was missing parts          244
145624    FAIR          3                       what was missing          244
145825    FAIR          3                    with no explanation          244
149513    FAIR          4                  data that was missing          244
150224    FAIR          4                explanation of what was          244
150993    FAIR          4                  handled data that was          244
151878    FAIR          4          information handled data that          244
153123    FAIR          4       missing information handled data          244
153131    FAIR          4                  missing parts with no          244
153444    FAIR          4                 no explanation of what          244
153916    FAIR          4                    of what was missing          244
154721    FAIR          4              parts with no explanation          244
157392    FAIR          4                 that was missing parts          244
159025    FAIR          4                     was missing or why          244
159026    FAIR          4                 was missing parts with          244
159292    FAIR          4                    what was missing or          244
159518    FAIR          4                 with no explanation of          244
163063    FAIR          5            data that was missing parts          244
163737    FAIR          5        explanation of what was missing          244
164476    FAIR          5          handled data that was missing          244
165330    FAIR          5      information handled data that was          244
166501    FAIR          5  missing information handled data that          244
166509    FAIR          5      missing parts with no explanation          244
166807    FAIR          5             no explanation of what was          244
167272    FAIR          5                 of what was missing or          244